### ISSUE TITLE
mailx command not working

### ISSUE THREAD

**Issue by zak-b2c2** [BuaBook/kdb-common#12]
Hi Jas,

**mailx** command from mail library is not working as expected for me, I think the flags are not made for **mailx**, or maybe I have the wrong **mailx** installed ( I did use `sudo apt-get install mailutils`)

Example of failure:

```
q).mail.send `to`subject`body`from!(`$"zak@b2c2.com";"Test email";"Hello world";`$"kdb@b2c2.com")
2019.07.10 12:56:44.607 INFO base ubuntu 0 Sending e-mail [ To: zak@b2c2.com ] [ Subject: Test email ] [ Mail Cmd: mailx ]
From: kdb@b2c2.com: No such file or directory
2019.07.10 12:56:44.611 ERROR base ubuntu 0 System call failed: os
2019.07.10 12:56:44.611 ERROR base ubuntu 0 Failed to send e-mail [ To: zak@b2c2.com ] [ Subject: Test email ] [ Mail Cmd: mailx ]. Error - SystemCallFailedException
'EmailSendFailedException
  [0]  .mail.send `to`subject`body`from!(`$"zak@b2c2.com";"Test email";"Hello world";`$"kdb@b2c2.com")
       ^
```

Looks like **mailx** uses different arguments:

- `-a` is for attachments
- `-A` is for account as defined in `$HOME/.mailrc`
- `-r` is for from

Let me know if it makes sense.

Additionally it would be great to have an **account** or **extraArgs** key in dict as AWS requires SMTP flags to be passed so that mail can be routed through SES

Thanks,
Zak

**Comment by jasraj** [comment]
Hi Zak,

Yeah looks like the wrong version of mailutils is installed (it's crazy that the same command can have different command line args...)

This was written to use the BSD version of `mailx` (see https://github.com/BuaBook/kdb-common/wiki/mail.q).

I've added support for a different mail client `mutt` which I've had more success on, especially on CentOS. Give that a go and see how it goes.

Regarding SES configuration, the link in the wiki page is how I've set it up before (using `sendmail`). With that, there was no other information that needed to be sended with the `mailx` command. How are you configuring it?


Thanks
Jas

**Comment by zak-b2c2** [comment]
I guess I should learn to RTFM... Looks like on my Ubuntu box it was pointing to `s-nail` rather than `mailutils` you have to check  the symlinks pointing to `/etc/alternatives/mail`. Re-installed and re-configured everything with `postfix`. All good now, cheers. 

No luck on Amazon Linux, there is no `mailutils`, so using `mailx`, which explains the issue. Will try out with `mutt`

On the SES side, I created an account and then set up configuration in `$HOME/.mailrc` to below. However this only works with heirloom's `mailx`, not BSD's `mailx`. It avoids working with postfix etc ...
```
account kdb_alert {
set smtp-auth=login
set smtp=smtps://email-smtp.eu-west-1.amazonaws.com:465
set from="kdb-alerts@b2c2.net"
set smtp-auth-user=USERNAME
set smtp-auth-password=PASSWORD
set ssl-verify=ignore
}
```

Thanks,
Zak

**Comment by zak-b2c2** [comment]
Got `mutt` to work on Amazon Linux (I think it's essentially RHEL under the hood). Thanks for your time
