### ISSUE TITLE
Missing timeout in .ipc.connect

### ISSUE THREAD

**Issue by zak-b2c2** [BuaBook/kdb-common#27]
Hi Jas,

It looks like the **timeout** is not passed in to **hopen** as part of the arguments below?

https://github.com/BuaBook/kdb-common/blob/32f768fe0e140987828f00ce3031c2b253ef937a/src/ipc.q#L97

Thanks,
Zak

**Comment by jasraj** [comment]
Hi Zak,

You’re right - I’ve never noticed it (and it’s been in there for 3 years). 

I’ll get it fixed by the weekend.

Thanks for reporting it.

Jas

**Comment by zak-b2c2** [comment]
Same here, after 1 year my luck ran out last night

**Comment by jasraj** [comment]
Hi Zak,

This has been fixed now and I've created a new version with it in - [kdb-common-1.1.2-2020.02.01](https://github.com/BuaBook/kdb-common/releases/tag/kdb-common-1.1.2-2020.02.01).

Thanks
Jas
